### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by sademakn** [snototter/vitocpp#3]
Can you please prepare a benchmark for comparing with opencv , imutils, imageio , etc?

**Comment by snototter** [comment]
Thank you for your suggestions. The aim of this library is to a) wrap functionality I often had to reimplement and b) provide additional functionality (especially sensor streaming and visualizations) which was not available (at least in previous OpenCV versions). It started as a pure C++ library, Python bindings have been added later on.
That said, benchmarking this hobby project against OpenCV isn't meaningful, as OpenCV is used under-the-hood.
Regarding your other suggestions, `imutils` and `imageio` are Python packages - if you're working with Python, I would recommend these packages as setting up these via `pip` is way easier than manually building a C++ library with Python bindings.

Additionally, as this is just a hobby project of mine, I don't have the time resources to benchmark `vcp`'s Python bindings against `imutils` (which would be the most meaningful comparison).
